name: usm-shared-ai

services:
  python-ai-worker:
    build:
      context: ../../..
      dockerfile: Shared/AI/deployment/Dockerfile
    environment:
      USM_SHARED_AI_CONFIG_FILE: /app/config/appsettings.json
    volumes:
      - ../samples/appsettings.json:/app/config/appsettings.json:ro
