apiVersion: v1
kind: Secret
metadata:
  name: usm-runtime-secrets
  namespace: usm-platform
type: Opaque
data:
  ConnectionStrings__Postgres: SG9zdD1wb3N0Z3Jlcy1wcmltYXJ5LnVzbS1wbGF0Zm9ybS5zdmMuY2x1c3Rlci5sb2NhbDtQb3J0PTU0MzI7RGF0YWJhc2U9dXNtX2ludmVudG9yeTtVc2VybmFtZT11c21fYXBwO1Bhc3N3b3JkPVMzY3VyZVBAc3N3MHJkITtQb29saW5nPXRydWU7U1NMIE1vZGU9UmVxdWlyZTtUcnVzdCBTZXJ2ZXIgQ2VydGlmaWNhdGU9dHJ1ZQ==
  Postgres__Password: UzNjdXJlUEBzc3cwcmQh
  Redis__PasswordedConnectionString: cmVkaXMtbWFzdGVyLnVzbS1wbGF0Zm9ybS5zdmMuY2x1c3Rlci5sb2NhbDo2Mzc5LHBhc3N3b3JkPVIzZGlzIUNhY2hlLHNzbD1GYWxzZSxhYm9ydENvbm5lY3Q9RmFsc2U=
  RabbitMq__ConnectionString: YW1xcHM6Ly91c21fYXBwOk1RUEBzc3cwcmQhQHJhYmJpdG1xLnVzbS1wbGF0Zm9ybS5zdmMuY2x1c3Rlci5sb2NhbDo1NjcxL3VzbQ==
  Auth__ClientId: YWI0Yzc1ODQtZmNjNy00ZTNmLThjNWQtMmNhMzc2MzE5YmM0
  Auth__ClientSecret: blI3M1Y1YVg1RjdRMnpmRDFZMEt4QTNvUjJtVzlwUWY=
  Jwt__SigningKey: V21WeWIxUnlkWE4wTFVwWFZDMVRhV2R1YVc1bkxVdGxlUzB5TURJMkxUQTQ=
  Fido2__RpId: dXNtLmludmVudG9yeS5leGFtcGxlLmNvbQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-client-ca
  namespace: usm-platform
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJnakNDQVNpZ0F3SUJBZ0lVZnVhRTJOSjlvcU0rK2VKaHlUSnZ6a2NoR2Vjd0NnWUlLb1pJemowRUF3SXcKRmpFVU1CSUdBMVVFQXd3TFZYTk5JRU5CSUI4d0hoY05NalF3T0RBek1EQXdNREF3V2hjTk16UXdPREF4TURBdwpNREF3V2pBV01SUXdFZ1lEVlFRRERBdFZjMDFKRUVOQklCOHdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRoaTgrMmtjTUc4YkQ2MEJoL3QzWjUyUTk4OXI4Qkd0eGJ4WjFsWXRaU3VOT2FMWmx2VG0vRjRKQWQKUFg2Nm9mL2o1QzR6elprQkptanNvM0l3Y2pBT0JnTlZIUThCQWY4RUJBTUNBZ1F3RHdZRFZSMFRBUUgvQkFVdwpBd0VCL3pBZEJnTlZIUTRFRmdRVUd2WGgxQ0NmR3R0eGhzTjlWQURmdUNqVkxMNHdDZ1lJS29aSXpqMEVBd0lEClNRQXdSZ0loQUxMSFhkaTQ2U0hqaHhiSUxVZjY1T1N6WXA0L2dYWW96QlExQnNQaGc4eEFpRUE5aWQ4NXAwYUMKVjVVQXRHQisweFB2VEhqeS8zOXZGYWc4aWc0Q2MyTnN5QW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
