// <auto-generated />
using System;
using Iam.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Iam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IamDbContext))]
    partial class IamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("iam")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceApprovalPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalRoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("CrossDepartment")
                        .HasColumnType("boolean");

                    b.Property<string>("FromBuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FromDepartmentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganogramInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ToBuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ToDepartmentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("OrganogramInstanceId");

                    b.ToTable("instance_approval_paths", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceBuildingBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganogramInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParentBuildingBlockCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("OrganogramInstanceId");

                    b.HasIndex("InstanceId", "BuildingBlockCode")
                        .IsUnique();

                    b.ToTable("instance_building_blocks", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstancePermissionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganogramInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OrganogramInstanceId");

                    b.HasIndex("InstanceId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("instance_permissions", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstancePositionAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("CivilianCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("MilitaryCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrganogramInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("OrganogramInstanceId");

                    b.HasIndex("InstanceId", "BuildingBlockCode", "RoleCode")
                        .IsUnique();

                    b.ToTable("instance_position_allocations", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceRoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganogramInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("OrganogramInstanceId");

                    b.HasIndex("InstanceId", "RoleCode")
                        .IsUnique();

                    b.ToTable("instance_roles", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceRoleHierarchy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChildRoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganogramInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParentRoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("RankOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganogramInstanceId");

                    b.HasIndex("InstanceId", "ParentRoleCode", "ChildRoleCode")
                        .IsUnique();

                    b.ToTable("instance_role_hierarchies", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganogramInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("OrganogramInstanceId");

                    b.HasIndex("InstanceId", "RoleCode", "PermissionCode")
                        .IsUnique();

                    b.ToTable("instance_role_permissions", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.OrganizationalUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganogramInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("OrganogramInstanceId");

                    b.HasIndex("InstanceId", "UnitKey")
                        .IsUnique();

                    b.ToTable("organizational_units", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.OrganogramInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstanceCode")
                        .IsUnique();

                    b.ToTable("organogram_instances", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.OrganogramTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FirstInstantiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("organogram_templates", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.SuperAdminAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("super_admin_assignments", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateApprovalPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalRoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("CrossDepartment")
                        .HasColumnType("boolean");

                    b.Property<string>("FromBuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FromDepartmentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToBuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ToDepartmentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("WorkflowCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("template_approval_paths", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateBuildingBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParentBuildingBlockCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "BuildingBlockCode")
                        .IsUnique();

                    b.ToTable("template_building_blocks", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParentDepartmentCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "DepartmentCode")
                        .IsUnique();

                    b.ToTable("template_departments", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplatePermissionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("template_permissions", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplatePositionAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("CivilianCount")
                        .HasColumnType("integer");

                    b.Property<int>("MilitaryCount")
                        .HasColumnType("integer");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "BuildingBlockCode", "RoleCode")
                        .IsUnique();

                    b.ToTable("template_position_allocations", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateRoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "RoleCode")
                        .IsUnique();

                    b.ToTable("template_roles", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateRoleHierarchy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChildRoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ParentRoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("RankOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "ParentRoleCode", "ChildRoleCode")
                        .IsUnique();

                    b.ToTable("template_role_hierarchies", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "RoleCode", "PermissionCode")
                        .IsUnique();

                    b.ToTable("template_role_permissions", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.UserOrganogramAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingBlockCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationalUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "InstanceId", "RoleCode", "OrganizationalUnitId")
                        .IsUnique();

                    b.ToTable("user_organogram_assignments", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Permissions.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("permissions", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("roles", "iam");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceApprovalPath", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramInstance", null)
                        .WithMany("ApprovalPaths")
                        .HasForeignKey("OrganogramInstanceId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceBuildingBlock", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramInstance", null)
                        .WithMany("BuildingBlocks")
                        .HasForeignKey("OrganogramInstanceId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstancePermissionDefinition", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramInstance", null)
                        .WithMany("Permissions")
                        .HasForeignKey("OrganogramInstanceId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstancePositionAllocation", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramInstance", null)
                        .WithMany("PositionAllocations")
                        .HasForeignKey("OrganogramInstanceId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceRoleDefinition", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramInstance", null)
                        .WithMany("Roles")
                        .HasForeignKey("OrganogramInstanceId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceRoleHierarchy", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramInstance", null)
                        .WithMany("RoleHierarchies")
                        .HasForeignKey("OrganogramInstanceId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.InstanceRolePermission", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramInstance", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("OrganogramInstanceId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.OrganizationalUnit", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramInstance", null)
                        .WithMany("OrganizationalUnits")
                        .HasForeignKey("OrganogramInstanceId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateApprovalPath", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramTemplate", null)
                        .WithMany("ApprovalPaths")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateBuildingBlock", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramTemplate", null)
                        .WithMany("BuildingBlocks")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateDepartment", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramTemplate", null)
                        .WithMany("Departments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplatePermissionDefinition", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramTemplate", null)
                        .WithMany("Permissions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplatePositionAllocation", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramTemplate", null)
                        .WithMany("PositionAllocations")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateRoleDefinition", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramTemplate", null)
                        .WithMany("Roles")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateRoleHierarchy", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramTemplate", null)
                        .WithMany("RoleHierarchies")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iam.Domain.Organograms.TemplateRolePermission", b =>
                {
                    b.HasOne("Iam.Domain.Organograms.OrganogramTemplate", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Iam.Domain.Permissions.Permission", b =>
                {
                    b.HasOne("Iam.Domain.Roles.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.OrganogramInstance", b =>
                {
                    b.Navigation("ApprovalPaths");

                    b.Navigation("BuildingBlocks");

                    b.Navigation("OrganizationalUnits");

                    b.Navigation("Permissions");

                    b.Navigation("PositionAllocations");

                    b.Navigation("RoleHierarchies");

                    b.Navigation("RolePermissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Iam.Domain.Organograms.OrganogramTemplate", b =>
                {
                    b.Navigation("ApprovalPaths");

                    b.Navigation("BuildingBlocks");

                    b.Navigation("Departments");

                    b.Navigation("Permissions");

                    b.Navigation("PositionAllocations");

                    b.Navigation("RoleHierarchies");

                    b.Navigation("RolePermissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Iam.Domain.Roles.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
